options = {
    "YearsCode": 0,
    "YearsCodePro": 0,
    "WorkExp": 0,
    "CodingActivities_Bootstrapping a business": 0,
    "CodingActivities_Contribute to open-source projects": 0,
    "CodingActivities_Freelance/contract work": 0,
    "CodingActivities_Hobby": 0,
    "CodingActivities_I don't code outside of work": 0,
    "CodingActivities_NA": 0,
    "CodingActivities_Other (please specify):": 0,
    "CodingActivities_Professional development or self-paced learning from online courses": 0,
    "CodingActivities_School or academic work": 0,
    "DatabaseHaveWorkedWith_BigQuery": 0,
    "DatabaseHaveWorkedWith_Cassandra": 0,
    "DatabaseHaveWorkedWith_Clickhouse": 0,
    "DatabaseHaveWorkedWith_Cloud Firestore": 0,
    "DatabaseHaveWorkedWith_Cockroachdb": 0,
    "DatabaseHaveWorkedWith_Cosmos DB": 0,
    "DatabaseHaveWorkedWith_Couch DB": 0,
    "DatabaseHaveWorkedWith_Couchbase": 0,
    "DatabaseHaveWorkedWith_Datomic": 0,
    "DatabaseHaveWorkedWith_DuckDB": 0,
    "DatabaseHaveWorkedWith_Dynamodb": 0,
    "DatabaseHaveWorkedWith_Elasticsearch": 0,
    "DatabaseHaveWorkedWith_Firebase Realtime Database": 0,
    "DatabaseHaveWorkedWith_Firebird": 0,
    "DatabaseHaveWorkedWith_H2": 0,
    "DatabaseHaveWorkedWith_IBM DB2": 0,
    "DatabaseHaveWorkedWith_InfluxDB": 0,
    "DatabaseHaveWorkedWith_MariaDB": 0,
    "DatabaseHaveWorkedWith_Microsoft Access": 0,
    "DatabaseHaveWorkedWith_Microsoft SQL Server": 0,
    "DatabaseHaveWorkedWith_MongoDB": 0,
    "DatabaseHaveWorkedWith_MySQL": 0,
    "DatabaseHaveWorkedWith_NA": 0,
    "DatabaseHaveWorkedWith_Neo4J": 0,
    "DatabaseHaveWorkedWith_Oracle": 0,
    "DatabaseHaveWorkedWith_PostgreSQL": 0,
    "DatabaseHaveWorkedWith_RavenDB": 0,
    "DatabaseHaveWorkedWith_Redis": 0,
    "DatabaseHaveWorkedWith_SQLite": 0,
    "DatabaseHaveWorkedWith_Snowflake": 0,
    "DatabaseHaveWorkedWith_Solr": 0,
    "DatabaseHaveWorkedWith_Supabase": 0,
    "DatabaseHaveWorkedWith_TiDB": 0,
    "DatabaseWantToWorkWith_Cassandra": 0,
    "DatabaseWantToWorkWith_BigQuery": 0,
    "DatabaseWantToWorkWith_Clickhouse": 0,
    "DatabaseWantToWorkWith_Cloud Firestore": 0,
    "DatabaseWantToWorkWith_Cockroachdb": 0,
    "DatabaseWantToWorkWith_Cosmos DB": 0,
    "DatabaseWantToWorkWith_Couch DB": 0,
    "DatabaseWantToWorkWith_Couchbase": 0,
    "DatabaseWantToWorkWith_Datomic": 0,
    "DatabaseWantToWorkWith_DuckDB": 0,
    "DatabaseWantToWorkWith_Dynamodb": 0,
    "DatabaseWantToWorkWith_Elasticsearch": 0,
    "DatabaseWantToWorkWith_Firebase Realtime Database": 0,
    "DatabaseWantToWorkWith_Firebird": 0,
    "DatabaseWantToWorkWith_H2": 0,
    "DatabaseWantToWorkWith_IBM DB2": 0,
    "DatabaseWantToWorkWith_InfluxDB": 0,
    "DatabaseWantToWorkWith_MariaDB": 0,
    "DatabaseWantToWorkWith_Microsoft Access": 0,
    "DatabaseWantToWorkWith_Microsoft SQL Server": 0,
    "DatabaseWantToWorkWith_MongoDB": 0,
    "DatabaseWantToWorkWith_MySQL": 0,
    "DatabaseWantToWorkWith_NA": 0,
    "DatabaseWantToWorkWith_Neo4J": 0,
    "DatabaseWantToWorkWith_Oracle": 0,
    "DatabaseWantToWorkWith_PostgreSQL": 0,
    "DatabaseWantToWorkWith_RavenDB": 0,
    "DatabaseWantToWorkWith_Redis": 0,
    "DatabaseWantToWorkWith_SQLite": 0,
    "DatabaseWantToWorkWith_Snowflake": 0,
    "DatabaseWantToWorkWith_Solr": 0,
    "DatabaseWantToWorkWith_Supabase": 0,
    "DatabaseWantToWorkWith_TiDB": 0,
    "Employment_Employed, full-time": 0,
    "Employment_Employed, part-time": 0,
    "Employment_I prefer not to say": 0,
    "Employment_Independent contractor, freelancer, or self-employed": 0,
    "Employment_NA": 0,
    "Employment_Not employed, and not looking for work": 0,
    "Employment_Not employed, but looking for work": 0,
    "Employment_Retired": 0,
    "Employment_Student, full-time": 0,
    "Employment_Student, part-time": 0,
    "LanguageHaveWorkedWith_C++": 0,
    "LanguageHaveWorkedWith_APL": 0,
    "LanguageHaveWorkedWith_Ada": 0,
    "LanguageHaveWorkedWith_Apex": 0,
    "LanguageHaveWorkedWith_Assembly": 0,
    "LanguageHaveWorkedWith_Bash/Shell (all shells)": 0,
    "LanguageHaveWorkedWith_C": 0,
    "LanguageHaveWorkedWith_C#": 0,
    "LanguageHaveWorkedWith_Clojure": 0,
    "LanguageHaveWorkedWith_Cobol": 0,
    "LanguageHaveWorkedWith_Crystal": 0,
    "LanguageHaveWorkedWith_Dart": 0,
    "LanguageHaveWorkedWith_Delphi": 0,
    "LanguageHaveWorkedWith_Elixir": 0,
    "LanguageHaveWorkedWith_Erlang": 0,
    "LanguageHaveWorkedWith_F#": 0,
    "LanguageHaveWorkedWith_Flow": 0,
    "LanguageHaveWorkedWith_Fortran": 0,
    "LanguageHaveWorkedWith_GDScript": 0,
    "LanguageHaveWorkedWith_Go": 0,
    "LanguageHaveWorkedWith_Groovy": 0,
    "LanguageHaveWorkedWith_HTML/CSS": 0,
    "LanguageHaveWorkedWith_Haskell": 0,
    "LanguageHaveWorkedWith_Java": 0,
    "LanguageHaveWorkedWith_JavaScript": 0,
    "LanguageHaveWorkedWith_Julia": 0,
    "LanguageHaveWorkedWith_Kotlin": 0,
    "LanguageHaveWorkedWith_Lisp": 0,
    "LanguageHaveWorkedWith_Lua": 0,
    "LanguageHaveWorkedWith_MATLAB": 0,
    "LanguageHaveWorkedWith_NA": 0,
    "LanguageHaveWorkedWith_Nim": 0,
    "LanguageHaveWorkedWith_OCaml": 0,
    "LanguageHaveWorkedWith_Objective-C": 0,
    "LanguageHaveWorkedWith_PHP": 0,
    "LanguageHaveWorkedWith_Perl": 0,
    "LanguageHaveWorkedWith_PowerShell": 0,
    "LanguageHaveWorkedWith_Prolog": 0,
    "LanguageHaveWorkedWith_Python": 0,
    "LanguageHaveWorkedWith_R": 0,
    "LanguageHaveWorkedWith_Raku": 0,
    "LanguageHaveWorkedWith_Ruby": 0,
    "LanguageHaveWorkedWith_Rust": 0,
    "LanguageHaveWorkedWith_SAS": 0,
    "LanguageHaveWorkedWith_SQL": 0,
    "LanguageHaveWorkedWith_Scala": 0,
    "LanguageHaveWorkedWith_Solidity": 0,
    "LanguageHaveWorkedWith_Swift": 0,
    "LanguageHaveWorkedWith_TypeScript": 0,
    "LanguageHaveWorkedWith_VBA": 0,
    "LanguageHaveWorkedWith_Visual Basic (.Net)": 0,
    "LanguageHaveWorkedWith_Zig": 0,
    "LanguageWantToWorkWith_APL": 0,
    "LanguageWantToWorkWith_Ada": 0,
    "LanguageWantToWorkWith_Apex": 0,
    "LanguageWantToWorkWith_Assembly": 0,
    "LanguageWantToWorkWith_Bash/Shell (all shells)": 0,
    "LanguageWantToWorkWith_C": 0,
    "LanguageWantToWorkWith_C#": 0,
    "LanguageWantToWorkWith_C++": 0,
    "LanguageWantToWorkWith_Clojure": 0,
    "LanguageWantToWorkWith_Cobol": 0,
    "LanguageWantToWorkWith_Crystal": 0,
    "LanguageWantToWorkWith_Dart": 0,
    "LanguageWantToWorkWith_Delphi": 0,
    "LanguageWantToWorkWith_Elixir": 0,
    "LanguageWantToWorkWith_Erlang": 0,
    "LanguageWantToWorkWith_F#": 0,
    "LanguageWantToWorkWith_Flow": 0,
    "LanguageWantToWorkWith_Fortran": 0,
    "LanguageWantToWorkWith_GDScript": 0,
    "LanguageWantToWorkWith_Go": 0,
    "LanguageWantToWorkWith_Groovy": 0,
    "LanguageWantToWorkWith_HTML/CSS": 0,
    "LanguageWantToWorkWith_Haskell": 0,
    "LanguageWantToWorkWith_Java": 0,
    "LanguageWantToWorkWith_JavaScript": 0,
    "LanguageWantToWorkWith_Julia": 0,
    "LanguageWantToWorkWith_Kotlin": 0,
    "LanguageWantToWorkWith_Lisp": 0,
    "LanguageWantToWorkWith_Lua": 0,
    "LanguageWantToWorkWith_MATLAB": 0,
    "LanguageWantToWorkWith_NA": 0,
    "LanguageWantToWorkWith_Nim": 0,
    "LanguageWantToWorkWith_OCaml": 0,
    "LanguageWantToWorkWith_Objective-C": 0,
    "LanguageWantToWorkWith_PHP": 0,
    "LanguageWantToWorkWith_Perl": 0,
    "LanguageWantToWorkWith_PowerShell": 0,
    "LanguageWantToWorkWith_Prolog": 0,
    "LanguageWantToWorkWith_Python": 0,
    "LanguageWantToWorkWith_R": 0,
    "LanguageWantToWorkWith_Raku": 0,
    "LanguageWantToWorkWith_Ruby": 0,
    "LanguageWantToWorkWith_Rust": 0,
    "LanguageWantToWorkWith_SAS": 0,
    "LanguageWantToWorkWith_SQL": 0,
    "LanguageWantToWorkWith_Scala": 0,
    "LanguageWantToWorkWith_Solidity": 0,
    "LanguageWantToWorkWith_Swift": 0,
    "LanguageWantToWorkWith_TypeScript": 0,
    "LanguageWantToWorkWith_VBA": 0,
    "LanguageWantToWorkWith_Visual Basic (.Net)": 0,
    "LanguageWantToWorkWith_Zig": 0,
    "LearnCode_Books / Physical media": 0,
    "LearnCode_Coding Bootcamp": 0,
    "LearnCode_Colleague": 0,
    "LearnCode_Friend or family member": 0,
    "LearnCode_Hackathons (virtual or in-person)": 0,
    "LearnCode_NA": 0,
    "LearnCode_On the job training": 0,
    "LearnCode_Online Courses or Certification": 0,
    "LearnCode_Other (please specify):": 0,
    "LearnCode_Other online resources (e.g., videos, blogs, forum)": 0,
    "LearnCode_School (i.e., University, College, etc)": 0,
    "LearnCodeCoursesCert_Codecademy": 0,
    "LearnCodeCoursesCert_Coursera": 0,
    "LearnCodeCoursesCert_NA": 0,
    "LearnCodeCoursesCert_Other": 0,
    "LearnCodeCoursesCert_Pluralsight": 0,
    "LearnCodeCoursesCert_Skillsoft": 0,
    "LearnCodeCoursesCert_Udacity": 0,
    "LearnCodeCoursesCert_Udemy": 0,
    "LearnCodeCoursesCert_edX": 0,
    "LearnCodeOnline_Auditory material (e.g., podcasts)": 0,
    "LearnCodeOnline_Blogs with tips and tricks": 0,
    "LearnCodeOnline_Books": 0,
    "LearnCodeOnline_Certification videos": 0,
    "LearnCodeOnline_Click to write Choice 20": 0,
    "LearnCodeOnline_Formal documentation provided by the owner of the tech": 0,
    "LearnCodeOnline_How-to videos": 0,
    "LearnCodeOnline_Interactive tutorial": 0,
    "LearnCodeOnline_NA": 0,
    "LearnCodeOnline_Online challenges (e.g., daily or weekly coding challenges)": 0,
    "LearnCodeOnline_Other (Please specify):": 0,
    "LearnCodeOnline_Programming Games": 0,
    "LearnCodeOnline_Recorded coding sessions": 0,
    "LearnCodeOnline_Stack Overflow": 0,
    "LearnCodeOnline_Video-based Online Courses": 0,
    "LearnCodeOnline_Written Tutorials": 0,
    "LearnCodeOnline_Written-based Online Courses": 0,
    "MiscTechHaveWorkedWith_.NET (5+) ": 0,
    "MiscTechHaveWorkedWith_.NET Framework (1.0 - 4.8)": 0,
    "MiscTechHaveWorkedWith_.NET MAUI": 0,
    "MiscTechHaveWorkedWith_Apache Kafka": 0,
    "MiscTechHaveWorkedWith_Apache Spark": 0,
    "MiscTechHaveWorkedWith_CUDA": 0,
    "MiscTechHaveWorkedWith_Capacitor": 0,
    "MiscTechHaveWorkedWith_Cordova": 0,
    "MiscTechHaveWorkedWith_Electron": 0,
    "MiscTechHaveWorkedWith_Flutter": 0,
    "MiscTechHaveWorkedWith_GTK": 0,
    "MiscTechHaveWorkedWith_Hadoop": 0,
    "MiscTechHaveWorkedWith_Hugging Face Transformers": 0,
    "MiscTechHaveWorkedWith_Ionic": 0,
    "MiscTechHaveWorkedWith_JAX": 0,
    "MiscTechHaveWorkedWith_Keras": 0,
    "MiscTechHaveWorkedWith_Ktor": 0,
    "MiscTechHaveWorkedWith_MFC": 0,
    "MiscTechHaveWorkedWith_Micronaut": 0,
    "MiscTechHaveWorkedWith_NA": 0,
    "MiscTechHaveWorkedWith_NumPy": 0,
    "MiscTechHaveWorkedWith_OpenGL": 0,
    "MiscTechHaveWorkedWith_Opencv": 0,
    "MiscTechHaveWorkedWith_Pandas": 0,
    "MiscTechHaveWorkedWith_Qt": 0,
    "MiscTechHaveWorkedWith_Quarkus": 0,
    "MiscTechHaveWorkedWith_RabbitMQ": 0,
    "MiscTechHaveWorkedWith_React Native": 0,
    "MiscTechHaveWorkedWith_Scikit-Learn": 0,
    "MiscTechHaveWorkedWith_Spring Framework": 0,
    "MiscTechHaveWorkedWith_SwiftUI": 0,
    "MiscTechHaveWorkedWith_Tauri": 0,
    "MiscTechHaveWorkedWith_TensorFlow": 0,
    "MiscTechHaveWorkedWith_Tidyverse": 0,
    "MiscTechHaveWorkedWith_Torch/PyTorch": 0,
    "MiscTechHaveWorkedWith_Uno Platform": 0,
    "MiscTechHaveWorkedWith_Xamarin": 0,
    "MiscTechWantToWorkWith_.NET (5+) ": 0,
    "MiscTechWantToWorkWith_.NET Framework (1.0 - 4.8)": 0,
    "MiscTechWantToWorkWith_.NET MAUI": 0,
    "MiscTechWantToWorkWith_Apache Kafka": 0,
    "MiscTechWantToWorkWith_Apache Spark": 0,
    "MiscTechWantToWorkWith_CUDA": 0,
    "MiscTechWantToWorkWith_Capacitor": 0,
    "MiscTechWantToWorkWith_Cordova": 0,
    "MiscTechWantToWorkWith_Electron": 0,
    "MiscTechWantToWorkWith_Flutter": 0,
    "MiscTechWantToWorkWith_GTK": 0,
    "MiscTechWantToWorkWith_Hadoop": 0,
    "MiscTechWantToWorkWith_Hugging Face Transformers": 0,
    "MiscTechWantToWorkWith_Ionic": 0,
    "MiscTechWantToWorkWith_JAX": 0,
    "MiscTechWantToWorkWith_Keras": 0,
    "MiscTechWantToWorkWith_Ktor": 0,
    "MiscTechWantToWorkWith_MFC": 0,
    "MiscTechWantToWorkWith_Micronaut": 0,
    "MiscTechWantToWorkWith_NA": 0,
    "MiscTechWantToWorkWith_NumPy": 0,
    "MiscTechWantToWorkWith_OpenGL": 0,
    "MiscTechWantToWorkWith_Opencv": 0,
    "MiscTechWantToWorkWith_Pandas": 0,
    "MiscTechWantToWorkWith_Qt": 0,
    "MiscTechWantToWorkWith_Quarkus": 0,
    "MiscTechWantToWorkWith_RabbitMQ": 0,
    "MiscTechWantToWorkWith_React Native": 0,
    "MiscTechWantToWorkWith_Scikit-Learn": 0,
    "MiscTechWantToWorkWith_Spring Framework": 0,
    "MiscTechWantToWorkWith_SwiftUI": 0,
    "MiscTechWantToWorkWith_Tauri": 0,
    "MiscTechWantToWorkWith_TensorFlow": 0,
    "MiscTechWantToWorkWith_Tidyverse": 0,
    "MiscTechWantToWorkWith_Torch/PyTorch": 0,
    "MiscTechWantToWorkWith_Uno Platform": 0,
    "MiscTechWantToWorkWith_Xamarin": 0,
    "NEWCollabToolsHaveWorkedWith_Android Studio": 0,
    "NEWCollabToolsHaveWorkedWith_Atom": 0,
    "NEWCollabToolsHaveWorkedWith_BBEdit": 0,
    "NEWCollabToolsHaveWorkedWith_CLion": 0,
    "NEWCollabToolsHaveWorkedWith_Code::Blocks": 0,
    "NEWCollabToolsHaveWorkedWith_DataGrip": 0,
    "NEWCollabToolsHaveWorkedWith_Eclipse": 0,
    "NEWCollabToolsHaveWorkedWith_Emacs": 0,
    "NEWCollabToolsHaveWorkedWith_Fleet": 0,
    "NEWCollabToolsHaveWorkedWith_Geany": 0,
    "NEWCollabToolsHaveWorkedWith_Goland": 0,
    "NEWCollabToolsHaveWorkedWith_Helix": 0,
    "NEWCollabToolsHaveWorkedWith_IPython": 0,
    "NEWCollabToolsHaveWorkedWith_IntelliJ IDEA": 0,
    "NEWCollabToolsHaveWorkedWith_Jupyter Notebook/JupyterLab": 0,
    "NEWCollabToolsHaveWorkedWith_Kate": 0,
    "NEWCollabToolsHaveWorkedWith_Micro": 0,
    "NEWCollabToolsHaveWorkedWith_NA": 0,
    "NEWCollabToolsHaveWorkedWith_Nano": 0,
    "NEWCollabToolsHaveWorkedWith_Neovim": 0,
    "NEWCollabToolsHaveWorkedWith_Netbeans": 0,
    "NEWCollabToolsHaveWorkedWith_Notepad++": 0,
    "NEWCollabToolsHaveWorkedWith_Nova": 0,
    "NEWCollabToolsHaveWorkedWith_PhpStorm": 0,
    "NEWCollabToolsHaveWorkedWith_PyCharm": 0,
    "NEWCollabToolsHaveWorkedWith_Qt Creator": 0,
    "NEWCollabToolsHaveWorkedWith_RStudio": 0,
    "NEWCollabToolsHaveWorkedWith_Rad Studio (Delphi, C++ Builder)": 0,
    "NEWCollabToolsHaveWorkedWith_Rider": 0,
    "NEWCollabToolsHaveWorkedWith_RubyMine": 0,
    "NEWCollabToolsHaveWorkedWith_Spyder": 0,
    "NEWCollabToolsHaveWorkedWith_Sublime Text": 0,
    "NEWCollabToolsHaveWorkedWith_TextMate": 0,
    "NEWCollabToolsHaveWorkedWith_VSCodium": 0,
    "NEWCollabToolsHaveWorkedWith_Vim": 0,
    "NEWCollabToolsHaveWorkedWith_Visual Studio": 0,
    "NEWCollabToolsHaveWorkedWith_Visual Studio Code": 0,
    "NEWCollabToolsHaveWorkedWith_WebStorm": 0,
    "NEWCollabToolsHaveWorkedWith_Xcode": 0,
    "NEWCollabToolsHaveWorkedWith_condo": 0,
    "NEWCollabToolsWantToWorkWith_Android Studio": 0,
    "NEWCollabToolsWantToWorkWith_Atom": 0,
    "NEWCollabToolsWantToWorkWith_BBEdit": 0,
    "NEWCollabToolsWantToWorkWith_CLion": 0,
    "NEWCollabToolsWantToWorkWith_Code::Blocks": 0,
    "NEWCollabToolsWantToWorkWith_DataGrip": 0,
    "NEWCollabToolsWantToWorkWith_Eclipse": 0,
    "NEWCollabToolsWantToWorkWith_Emacs": 0,
    "NEWCollabToolsWantToWorkWith_Fleet": 0,
    "NEWCollabToolsWantToWorkWith_Geany": 0,
    "NEWCollabToolsWantToWorkWith_Goland": 0,
    "NEWCollabToolsWantToWorkWith_Helix": 0,
    "NEWCollabToolsWantToWorkWith_IPython": 0,
    "NEWCollabToolsWantToWorkWith_IntelliJ IDEA": 0,
    "NEWCollabToolsWantToWorkWith_Jupyter Notebook/JupyterLab": 0,
    "NEWCollabToolsWantToWorkWith_Kate": 0,
    "NEWCollabToolsWantToWorkWith_Micro": 0,
    "NEWCollabToolsWantToWorkWith_NA": 0,
    "NEWCollabToolsWantToWorkWith_Nano": 0,
    "NEWCollabToolsWantToWorkWith_Neovim": 0,
    "NEWCollabToolsWantToWorkWith_Netbeans": 0,
    "NEWCollabToolsWantToWorkWith_Notepad++": 0,
    "NEWCollabToolsWantToWorkWith_Nova": 0,
    "NEWCollabToolsWantToWorkWith_PhpStorm": 0,
    "NEWCollabToolsWantToWorkWith_PyCharm": 0,
    "NEWCollabToolsWantToWorkWith_Qt Creator": 0,
    "NEWCollabToolsWantToWorkWith_RStudio": 0,
    "NEWCollabToolsWantToWorkWith_Rad Studio (Delphi, C++ Builder)": 0,
    "NEWCollabToolsWantToWorkWith_Rider": 0,
    "NEWCollabToolsWantToWorkWith_RubyMine": 0,
    "NEWCollabToolsWantToWorkWith_Spyder": 0,
    "NEWCollabToolsWantToWorkWith_Sublime Text": 0,
    "NEWCollabToolsWantToWorkWith_TextMate": 0,
    "NEWCollabToolsWantToWorkWith_VSCodium": 0,
    "NEWCollabToolsWantToWorkWith_Vim": 0,
    "NEWCollabToolsWantToWorkWith_Visual Studio": 0,
    "NEWCollabToolsWantToWorkWith_Visual Studio Code": 0,
    "NEWCollabToolsWantToWorkWith_WebStorm": 0,
    "NEWCollabToolsWantToWorkWith_Xcode": 0,
    "NEWCollabToolsWantToWorkWith_condo": 0,
    "PlatformHaveWorkedWith_Amazon Web Services (AWS)": 0,
    "PlatformHaveWorkedWith_Cloudflare": 0,
    "PlatformHaveWorkedWith_Colocation": 0,
    "PlatformHaveWorkedWith_Digital Ocean": 0,
    "PlatformHaveWorkedWith_Firebase": 0,
    "PlatformHaveWorkedWith_Fly.io": 0,
    "PlatformHaveWorkedWith_Google Cloud": 0,
    "PlatformHaveWorkedWith_Heroku": 0,
    "PlatformHaveWorkedWith_Hetzner": 0,
    "PlatformHaveWorkedWith_IBM Cloud Or Watson": 0,
    "PlatformHaveWorkedWith_Linode, now Akamai": 0,
    "PlatformHaveWorkedWith_Managed Hosting": 0,
    "PlatformHaveWorkedWith_Microsoft Azure": 0,
    "PlatformHaveWorkedWith_NA": 0,
    "PlatformHaveWorkedWith_Netlify": 0,
    "PlatformHaveWorkedWith_OVH": 0,
    "PlatformHaveWorkedWith_OpenShift": 0,
    "PlatformHaveWorkedWith_OpenStack": 0,
    "PlatformHaveWorkedWith_Oracle Cloud Infrastructure (OCI)": 0,
    "PlatformHaveWorkedWith_Render": 0,
    "PlatformHaveWorkedWith_Scaleway": 0,
    "PlatformHaveWorkedWith_VMware": 0,
    "PlatformHaveWorkedWith_Vercel": 0,
    "PlatformHaveWorkedWith_Vultr": 0,
    "PlatformWantToWorkWith_Amazon Web Services (AWS)": 0,
    "PlatformWantToWorkWith_Cloudflare": 0,
    "PlatformWantToWorkWith_Colocation": 0,
    "PlatformWantToWorkWith_Digital Ocean": 0,
    "PlatformWantToWorkWith_Firebase": 0,
    "PlatformWantToWorkWith_Fly.io": 0,
    "PlatformWantToWorkWith_Google Cloud": 0,
    "PlatformWantToWorkWith_Heroku": 0,
    "PlatformWantToWorkWith_Hetzner": 0,
    "PlatformWantToWorkWith_IBM Cloud Or Watson": 0,
    "PlatformWantToWorkWith_Linode, now Akamai": 0,
    "PlatformWantToWorkWith_Managed Hosting": 0,
    "PlatformWantToWorkWith_Microsoft Azure": 0,
    "PlatformWantToWorkWith_NA": 0,
    "PlatformWantToWorkWith_Netlify": 0,
    "PlatformWantToWorkWith_OVH": 0,
    "PlatformWantToWorkWith_OpenShift": 0,
    "PlatformWantToWorkWith_OpenStack": 0,
    "PlatformWantToWorkWith_Oracle Cloud Infrastructure (OCI)": 0,
    "PlatformWantToWorkWith_Render": 0,
    "PlatformWantToWorkWith_Scaleway": 0,
    "PlatformWantToWorkWith_VMware": 0,
    "PlatformWantToWorkWith_Vercel": 0,
    "PlatformWantToWorkWith_Vultr": 0,
    "ProfessionalTech_AI-assisted technology tool(s)": 0,
    "ProfessionalTech_Automated testing": 0,
    "ProfessionalTech_Continuous integration (CI) and (more often) continuous delivery": 0,
    "ProfessionalTech_DevOps function": 0,
    "ProfessionalTech_Developer portal or other central places to find tools/services": 0,
    "ProfessionalTech_Innersource initiative": 0,
    "ProfessionalTech_Microservices": 0,
    "ProfessionalTech_NA": 0,
    "ProfessionalTech_None of these": 0,
    "ProfessionalTech_Observability tools": 0,
    "ToolsTechHaveWorkedWith_APT": 0,
    "ToolsTechHaveWorkedWith_Ansible": 0,
    "ToolsTechHaveWorkedWith_Ant": 0,
    "ToolsTechHaveWorkedWith_Boost.Test": 0,
    "ToolsTechHaveWorkedWith_Bun": 0,
    "ToolsTechHaveWorkedWith_CMake": 0,
    "ToolsTechHaveWorkedWith_CUTE": 0,
    "ToolsTechHaveWorkedWith_Cargo": 0,
    "ToolsTechHaveWorkedWith_Catch2": 0,
    "ToolsTechHaveWorkedWith_Chef": 0,
    "ToolsTechHaveWorkedWith_Chocolatey": 0,
    "ToolsTechHaveWorkedWith_Composer": 0,
    "ToolsTechHaveWorkedWith_Dagger": 0,
    "ToolsTechHaveWorkedWith_Docker": 0,
    "ToolsTechHaveWorkedWith_ELFspy": 0,
    "ToolsTechHaveWorkedWith_GNU GCC": 0,
    "ToolsTechHaveWorkedWith_Godot": 0,
    "ToolsTechHaveWorkedWith_Google Test": 0,
    "ToolsTechHaveWorkedWith_Gradle": 0,
    "ToolsTechHaveWorkedWith_Homebrew": 0,
    "ToolsTechHaveWorkedWith_Kubernetes": 0,
    'ToolsTechHaveWorkedWith_LLVM"s Clang': 0,
    "ToolsTechHaveWorkedWith_MSBuild": 0,
    "ToolsTechHaveWorkedWith_MSVC": 0,
    "ToolsTechHaveWorkedWith_Make": 0,
    "ToolsTechHaveWorkedWith_Maven (build tool)": 0,
    "ToolsTechHaveWorkedWith_Meson": 0,
    "ToolsTechHaveWorkedWith_NA": 0,
    "ToolsTechHaveWorkedWith_Ninja": 0,
    "ToolsTechHaveWorkedWith_Nix": 0,
    "ToolsTechHaveWorkedWith_NuGet": 0,
    "ToolsTechHaveWorkedWith_Pacman": 0,
    "ToolsTechHaveWorkedWith_Pip": 0,
    "ToolsTechHaveWorkedWith_Podman": 0,
    "ToolsTechHaveWorkedWith_Pulumi": 0,
    "ToolsTechHaveWorkedWith_Puppet": 0,
    "ToolsTechHaveWorkedWith_QMake": 0,
    "ToolsTechHaveWorkedWith_SCons": 0,
    "ToolsTechHaveWorkedWith_Terraform": 0,
    "ToolsTechHaveWorkedWith_Unity 3D": 0,
    "ToolsTechHaveWorkedWith_Unreal Engine": 0,
    "ToolsTechHaveWorkedWith_Visual Studio Solution": 0,
    "ToolsTechHaveWorkedWith_Vite": 0,
    "ToolsTechHaveWorkedWith_Wasmer": 0,
    "ToolsTechHaveWorkedWith_Webpack": 0,
    "ToolsTechHaveWorkedWith_Yarn": 0,
    "ToolsTechHaveWorkedWith_bandit": 0,
    "ToolsTechHaveWorkedWith_build2": 0,
    "ToolsTechHaveWorkedWith_cppunit": 0,
    "ToolsTechHaveWorkedWith_doctest": 0,
    "ToolsTechHaveWorkedWith_lest": 0,
    "ToolsTechHaveWorkedWith_liblittletest": 0,
    "ToolsTechHaveWorkedWith_npm": 0,
    "ToolsTechHaveWorkedWith_pnpm": 0,
    "ToolsTechHaveWorkedWith_snitch": 0,
    "ToolsTechHaveWorkedWith_tunit": 0,
    "ToolsTechWantToWorkWith_APT": 0,
    "ToolsTechWantToWorkWith_Ansible": 0,
    "ToolsTechWantToWorkWith_Ant": 0,
    "ToolsTechWantToWorkWith_Boost.Test": 0,
    "ToolsTechWantToWorkWith_Bun": 0,
    "ToolsTechWantToWorkWith_CMake": 0,
    "ToolsTechWantToWorkWith_CUTE": 0,
    "ToolsTechWantToWorkWith_Cargo": 0,
    "ToolsTechWantToWorkWith_Catch2": 0,
    "ToolsTechWantToWorkWith_Chef": 0,
    "ToolsTechWantToWorkWith_Chocolatey": 0,
    "ToolsTechWantToWorkWith_Composer": 0,
    "ToolsTechWantToWorkWith_Dagger": 0,
    "ToolsTechWantToWorkWith_Docker": 0,
    "ToolsTechWantToWorkWith_ELFspy": 0,
    "ToolsTechWantToWorkWith_GNU GCC": 0,
    "ToolsTechWantToWorkWith_Godot": 0,
    "ToolsTechWantToWorkWith_Google Test": 0,
    "ToolsTechWantToWorkWith_Gradle": 0,
    "ToolsTechWantToWorkWith_Homebrew": 0,
    "ToolsTechWantToWorkWith_Kubernetes": 0,
    'ToolsTechWantToWorkWith_LLVM"s Clang': 0,
    "ToolsTechWantToWorkWith_MSBuild": 0,
    "ToolsTechWantToWorkWith_MSVC": 0,
    "ToolsTechWantToWorkWith_Make": 0,
    "ToolsTechWantToWorkWith_Maven (build tool)": 0,
    "ToolsTechWantToWorkWith_Meson": 0,
    "ToolsTechWantToWorkWith_NA": 0,
    "ToolsTechWantToWorkWith_Ninja": 0,
    "ToolsTechWantToWorkWith_Nix": 0,
    "ToolsTechWantToWorkWith_NuGet": 0,
    "ToolsTechWantToWorkWith_Pacman": 0,
    "ToolsTechWantToWorkWith_Pip": 0,
    "ToolsTechWantToWorkWith_Podman": 0,
    "ToolsTechWantToWorkWith_Pulumi": 0,
    "ToolsTechWantToWorkWith_Puppet": 0,
    "ToolsTechWantToWorkWith_QMake": 0,
    "ToolsTechWantToWorkWith_SCons": 0,
    "ToolsTechWantToWorkWith_Terraform": 0,
    "ToolsTechWantToWorkWith_Unity 3D": 0,
    "ToolsTechWantToWorkWith_Unreal Engine": 0,
    "ToolsTechWantToWorkWith_Visual Studio Solution": 0,
    "ToolsTechWantToWorkWith_Vite": 0,
    "ToolsTechWantToWorkWith_Wasmer": 0,
    "ToolsTechWantToWorkWith_Webpack": 0,
    "ToolsTechWantToWorkWith_Yarn": 0,
    "ToolsTechWantToWorkWith_bandit": 0,
    "ToolsTechWantToWorkWith_build2": 0,
    "ToolsTechWantToWorkWith_cppunit": 0,
    "ToolsTechWantToWorkWith_doctest": 0,
    "ToolsTechWantToWorkWith_lest": 0,
    "ToolsTechWantToWorkWith_liblittletest": 0,
    "ToolsTechWantToWorkWith_npm": 0,
    "ToolsTechWantToWorkWith_pnpm": 0,
    "ToolsTechWantToWorkWith_snitch": 0,
    "ToolsTechWantToWorkWith_tunit": 0,
    "WebframeHaveWorkedWith_ASP.NET": 0,
    "WebframeHaveWorkedWith_ASP.NET CORE": 0,
    "WebframeHaveWorkedWith_Angular": 0,
    "WebframeHaveWorkedWith_AngularJS": 0,
    "WebframeHaveWorkedWith_Blazor": 0,
    "WebframeHaveWorkedWith_CodeIgniter": 0,
    "WebframeHaveWorkedWith_Deno": 0,
    "WebframeHaveWorkedWith_Django": 0,
    "WebframeHaveWorkedWith_Drupal": 0,
    "WebframeHaveWorkedWith_Elm": 0,
    "WebframeHaveWorkedWith_Express": 0,
    "WebframeHaveWorkedWith_FastAPI": 0,
    "WebframeHaveWorkedWith_Fastify": 0,
    "WebframeHaveWorkedWith_Flask": 0,
    "WebframeHaveWorkedWith_Gatsby": 0,
    "WebframeHaveWorkedWith_Laravel": 0,
    "WebframeHaveWorkedWith_Lit": 0,
    "WebframeHaveWorkedWith_NA": 0,
    "WebframeHaveWorkedWith_NestJS": 0,
    "WebframeHaveWorkedWith_Next.js": 0,
    "WebframeHaveWorkedWith_Node.js": 0,
    "WebframeHaveWorkedWith_Nuxt.js": 0,
    "WebframeHaveWorkedWith_Phoenix": 0,
    "WebframeHaveWorkedWith_Play Framework": 0,
    "WebframeHaveWorkedWith_Qwik": 0,
    "WebframeHaveWorkedWith_React": 0,
    "WebframeHaveWorkedWith_Remix": 0,
    "WebframeHaveWorkedWith_Ruby on Rails": 0,
    "WebframeHaveWorkedWith_Solid.js": 0,
    "WebframeHaveWorkedWith_Spring Boot": 0,
    "WebframeHaveWorkedWith_Svelte": 0,
    "WebframeHaveWorkedWith_Symfony": 0,
    "WebframeHaveWorkedWith_Vue.js": 0,
    "WebframeHaveWorkedWith_WordPress": 0,
    "WebframeHaveWorkedWith_jQuery": 0,
    "WebframeWantToWorkWith_ASP.NET": 0,
    "WebframeWantToWorkWith_ASP.NET CORE": 0,
    "WebframeWantToWorkWith_Angular": 0,
    "WebframeWantToWorkWith_AngularJS": 0,
    "WebframeWantToWorkWith_Blazor": 0,
    "WebframeWantToWorkWith_CodeIgniter": 0,
    "WebframeWantToWorkWith_Deno": 0,
    "WebframeWantToWorkWith_Django": 0,
    "WebframeWantToWorkWith_Drupal": 0,
    "WebframeWantToWorkWith_Elm": 0,
    "WebframeWantToWorkWith_Express": 0,
    "WebframeWantToWorkWith_FastAPI": 0,
    "WebframeWantToWorkWith_Fastify": 0,
    "WebframeWantToWorkWith_Flask": 0,
    "WebframeWantToWorkWith_Gatsby": 0,
    "WebframeWantToWorkWith_Laravel": 0,
    "WebframeWantToWorkWith_Lit": 0,
    "WebframeWantToWorkWith_NA": 0,
    "WebframeWantToWorkWith_NestJS": 0,
    "WebframeWantToWorkWith_Next.js": 0,
    "WebframeWantToWorkWith_Node.js": 0,
    "WebframeWantToWorkWith_Nuxt.js": 0,
    "WebframeWantToWorkWith_Phoenix": 0,
    "WebframeWantToWorkWith_Play Framework": 0,
    "WebframeWantToWorkWith_Qwik": 0,
    "WebframeWantToWorkWith_React": 0,
    "WebframeWantToWorkWith_Remix": 0,
    "WebframeWantToWorkWith_Ruby on Rails": 0,
    "WebframeWantToWorkWith_Solid.js": 0,
    "WebframeWantToWorkWith_Spring Boot": 0,
    "WebframeWantToWorkWith_Svelte": 0,
    "WebframeWantToWorkWith_Symfony": 0,
    "WebframeWantToWorkWith_Vue.js": 0,
    "WebframeWantToWorkWith_WordPress": 0,
    "WebframeWantToWorkWith_jQuery": 0,
    "ICorPM_NA": 0,
    "ICorPM_People manager": 0,
    "RemoteWork_In-person": 0,
    "RemoteWork_NA": 0,
    "RemoteWork_Remote": 0,
    "EdLevel_Bachelor's degree (B.A., B.S., B.Eng., etc.)": 0,
    "EdLevel_Master's degree (M.A., M.S., M.Eng., MBA, etc.)": 0,
    "EdLevel_NA": 0,
    "EdLevel_Primary/elementary school": 0,
    "EdLevel_Professional degree (JD, MD, Ph.D, Ed.D, etc.)": 0,
    "EdLevel_Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)": 0,
    "EdLevel_Some college/university study without earning a degree": 0,
    "EdLevel_Something else": 0,
    "DevType_Blockchain": 0,
    "DevType_Cloud infrastructure engineer": 0,
    "DevType_Data or business analyst": 0,
    "DevType_Data scientist or machine learning specialist": 0,
    "DevType_Database administrator": 0,
    "DevType_Designer": 0,
    "DevType_DevOps specialist": 0,
    "DevType_Developer Advocate": 0,
    "DevType_Developer Experience": 0,
    "DevType_Developer, QA or test": 0,
    "DevType_Developer, back-end": 0,
    "DevType_Developer, desktop or enterprise applications": 0,
    "DevType_Developer, embedded applications or devices": 0,
    "DevType_Developer, front-end": 0,
    "DevType_Developer, full-stack": 0,
    "DevType_Developer, game or graphics": 0,
    "DevType_Developer, mobile": 0,
    "DevType_Educator": 0,
    "DevType_Engineer, data": 0,
    "DevType_Engineer, site reliability": 0,
    "DevType_Engineering manager": 0,
    "DevType_Hardware Engineer": 0,
    "DevType_Marketing or sales professional": 0,
    "DevType_NA": 0,
    "DevType_Other (please specify):": 0,
    "DevType_Product manager": 0,
    "DevType_Project manager": 0,
    "DevType_Research & Development role": 0,
    "DevType_Scientist": 0,
    "DevType_Security professional": 0,
    "DevType_Senior Executive (C-Suite, VP, etc.)": 0,
    "DevType_Student": 0,
    "DevType_System administrator": 0,
    "MainBranch_I am learning to code": 0,
    "MainBranch_I am not primarily a developer, but I write code sometimes as part of my work/studies": 0,
    "MainBranch_I code primarily as a hobby": 0,
    "MainBranch_I used to be a developer by profession, but no longer am": 0,
    "MainBranch_None of these": 0,
    "Country_Albania": 0,
    "Country_Algeria": 0,
    "Country_Andorra": 0,
    "Country_Angola": 0,
    "Country_Antigua and Barbuda": 0,
    "Country_Argentina": 0,
    "Country_Armenia": 0,
    "Country_Australia": 0,
    "Country_Austria": 0,
    "Country_Azerbaijan": 0,
    "Country_Bahamas": 0,
    "Country_Bahrain": 0,
    "Country_Bangladesh": 0,
    "Country_Barbados": 0,
    "Country_Belarus": 0,
    "Country_Belgium": 0,
    "Country_Belize": 0,
    "Country_Benin": 0,
    "Country_Bhutan": 0,
    "Country_Bolivia": 0,
    "Country_Bosnia and Herzegovina": 0,
    "Country_Botswana": 0,
    "Country_Brazil": 0,
    "Country_Brunei Darussalam": 0,
    "Country_Bulgaria": 0,
    "Country_Burkina Faso": 0,
    "Country_Burundi": 0,
    "Country_Cambodia": 0,
    "Country_Cameroon": 0,
    "Country_Canada": 0,
    "Country_Cape Verde": 0,
    "Country_Central African Republic": 0,
    "Country_Chile": 0,
    "Country_China": 0,
    "Country_Colombia": 0,
    "Country_Congo, Republic of the...": 0,
    "Country_Costa Rica": 0,
    "Country_Croatia": 0,
    "Country_Cuba": 0,
    "Country_Cyprus": 0,
    "Country_Czech Republic": 0,
    "Country_Côte d'Ivoire": 0,
    "Country_Democratic People's Republic of Korea": 0,
    "Country_Democratic Republic of the Congo": 0,
    "Country_Denmark": 0,
    "Country_Djibouti": 0,
    "Country_Dominica": 0,
    "Country_Dominican Republic": 0,
    "Country_Ecuador": 0,
    "Country_Egypt": 0,
    "Country_El Salvador": 0,
    "Country_Estonia": 0,
    "Country_Ethiopia": 0,
    "Country_Fiji": 0,
    "Country_Finland": 0,
    "Country_France": 0,
    "Country_Gabon": 0,
    "Country_Georgia": 0,
    "Country_Germany": 0,
    "Country_Ghana": 0,
    "Country_Greece": 0,
    "Country_Grenada": 0,
    "Country_Guatemala": 0,
    "Country_Guinea": 0,
    "Country_Guinea-Bissau": 0,
    "Country_Guyana": 0,
    "Country_Haiti": 0,
    "Country_Honduras": 0,
    "Country_Hong Kong (S.A.R.)": 0,
    "Country_Hungary": 0,
    "Country_Iceland": 0,
    "Country_India": 0,
    "Country_Indonesia": 0,
    "Country_Iran, Islamic Republic of...": 0,
    "Country_Iraq": 0,
    "Country_Ireland": 0,
    "Country_Isle of Man": 0,
    "Country_Israel": 0,
    "Country_Italy": 0,
    "Country_Jamaica": 0,
    "Country_Japan": 0,
    "Country_Jordan": 0,
    "Country_Kazakhstan": 0,
    "Country_Kenya": 0,
    "Country_Kosovo": 0,
    "Country_Kuwait": 0,
    "Country_Kyrgyzstan": 0,
    "Country_Lao People's Democratic Republic": 0,
    "Country_Latvia": 0,
    "Country_Lebanon": 0,
    "Country_Lesotho": 0,
    "Country_Liberia": 0,
    "Country_Libyan Arab Jamahiriya": 0,
    "Country_Liechtenstein": 0,
    "Country_Lithuania": 0,
    "Country_Luxembourg": 0,
    "Country_Madagascar": 0,
    "Country_Malawi": 0,
    "Country_Malaysia": 0,
    "Country_Maldives": 0,
    "Country_Mali": 0,
    "Country_Malta": 0,
    "Country_Marshall Islands": 0,
    "Country_Mauritania": 0,
    "Country_Mauritius": 0,
    "Country_Mexico": 0,
    "Country_Monaco": 0,
    "Country_Mongolia": 0,
    "Country_Montenegro": 0,
    "Country_Morocco": 0,
    "Country_Mozambique": 0,
    "Country_Myanmar": 0,
    "Country_NA": 0,
    "Country_Namibia": 0,
    "Country_Nepal": 0,
    "Country_Netherlands": 0,
    "Country_New Zealand": 0,
    "Country_Nicaragua": 0,
    "Country_Niger": 0,
    "Country_Nigeria": 0,
    "Country_Nomadic": 0,
    "Country_North Korea": 0,
    "Country_Norway": 0,
    "Country_Oman": 0,
    "Country_Pakistan": 0,
    "Country_Palau": 0,
    "Country_Palestine": 0,
    "Country_Panama": 0,
    "Country_Paraguay": 0,
    "Country_Peru": 0,
    "Country_Philippines": 0,
    "Country_Poland": 0,
    "Country_Portugal": 0,
    "Country_Qatar": 0,
    "Country_Republic of Korea": 0,
    "Country_Republic of Moldova": 0,
    "Country_Romania": 0,
    "Country_Russian Federation": 0,
    "Country_Rwanda": 0,
    "Country_Saint Kitts and Nevis": 0,
    "Country_Saint Lucia": 0,
    "Country_Saint Vincent and the Grenadines": 0,
    "Country_Samoa": 0,
    "Country_San Marino": 0,
    "Country_Saudi Arabia": 0,
    "Country_Senegal": 0,
    "Country_Serbia": 0,
    "Country_Sierra Leone": 0,
    "Country_Singapore": 0,
    "Country_Slovakia": 0,
    "Country_Slovenia": 0,
    "Country_Somalia": 0,
    "Country_South Africa": 0,
    "Country_South Korea": 0,
    "Country_Spain": 0,
    "Country_Sri Lanka": 0,
    "Country_Sudan": 0,
    "Country_Suriname": 0,
    "Country_Swaziland": 0,
    "Country_Sweden": 0,
    "Country_Switzerland": 0,
    "Country_Syrian Arab Republic": 0,
    "Country_Taiwan": 0,
    "Country_Tajikistan": 0,
    "Country_Thailand": 0,
    "Country_The former Yugoslav Republic of Macedonia": 0,
    "Country_Timor-Leste": 0,
    "Country_Togo": 0,
    "Country_Trinidad and Tobago": 0,
    "Country_Tunisia": 0,
    "Country_Turkey": 0,
    "Country_Turkmenistan": 0,
    "Country_Uganda": 0,
    "Country_Ukraine": 0,
    "Country_United Arab Emirates": 0,
    "Country_United Kingdom of Great Britain and Northern Ireland": 0,
    "Country_United Republic of Tanzania": 0,
    "Country_United States of America": 0,
    "Country_Uruguay": 0,
    "Country_Uzbekistan": 0,
    "Country_Venezuela, Bolivarian Republic of...": 0,
    "Country_Viet Nam": 0,
    "Country_Yemen": 0,
    "Country_Zambia": 0,
    "Country_Zimbabwe": 0,
    "Industry_Financial Services": 0,
    "Industry_Healthcare": 0,
    "Industry_Higher Education": 0,
    "Industry_Information Services, IT, Software Development, or other Technology": 0,
    "Industry_Insurance": 0,
    "Industry_Legal Services": 0,
    "Industry_Manufacturing, Transportation, or Supply Chain": 0,
    "Industry_NA": 0,
    "Industry_Oil & Gas": 0,
    "Industry_Other": 0,
    "Industry_Retail and Consumer Services": 0,
    "Industry_Wholesale": 0,
}



persons = [
    {
        "name": "Rajesh Sharma",
        "university": "BITS WILP",
        "course": "B.Tech in Computer Science",
        "company_name": "InnovateTech Solutions Pvt. Ltd.",
        "designation": "Senior Software Engineer",
        "image" : "image1.png"
    },
    {
        "name": "Priya Patel",
        "university": "BITS WILP",
        "course": "M.Tech in Data Science",
        "company_name": "DataMinds Analytics Pvt. Ltd.",
        "designation": "Data Scientist",
        "image" : "image2.png"
    },
    {
        "name": "Arjun Singh",
        "university": "BITS WILP",
        "course": "B.Tech in Information Technology",
        "company_name": "CyberTech Innovations Pvt. Ltd.",
        "designation": "Cybersecurity Analyst",
        "image" : "image3.png"
    },
    {
        "name": "Neha Gupta",
        "university": "BITS WILP",
        "course": "B.Tech in Computer Science",
        "company_name": "CloudCompass Technologies Pvt. Ltd.",
        "designation": "Cloud Solutions Architect",
        "image" : "image5.jpg"
    },
    {
        "name": "Vikram Mehta",
        "university": "BITS WILP",
        "course": "B.Tech in Computer Science",
        "company_name": "AI Dynamics Pvt. Ltd.",
        "designation": "Artificial Intelligence Engineer",
        "image" : "image4.jpg"
    },
    {
        "name": "Ananya Banerjee",
        "university": "BITS WILP",
        "course": "B.Tech in Computer Science",
        "company_name": "WebWizards Pvt. Ltd.",
        "designation": "Web Developer",
        "image" : "image6.jpg"
    },
    {
        "name": "Rahul Desai",
        "university": "BITS WILP",
        "course": "B.Tech in Computer Science",
        "company_name": "CodeCrafters Technologies Pvt. Ltd.",
        "designation": "Software Development Manager",
        "image" : "image8.png"
    },
    {
        "name": "Ayush Khanna",
        "university": "BITS WILP",
        "course": "B.Tech in Electrical Engineering",
        "company_name": "NetworkNinjas Pvt. Ltd.",
        "designation": "Network Engineer",
        "image" : "image9.png"
    },
    {
        "name": "Deepak Choudhary",
        "university": "BITS WILP",
        "course": "B.Tech in Computer Science",
        "company_name": "MobileMasters Pvt. Ltd.",
        "designation": "Mobile App Developer",
        "image" : "image10.jpg"
    },
    {
        "name": "Sumit Reddy",
        "university": "BITS WILP",
        "course": "B.Tech in Information Technology",
        "company_name": "TechSupport Systems Pvt. Ltd.",
        "designation": "Technical Support Specialist",
        "image" : "image11.png"
    },
    {
        "name": "Aman Verma",
        "university": "BITS WILP",
        "course": "B.Tech in Computer Science",
        "company_name": "QA Innovations Pvt. Ltd.",
        "designation": "Quality Assurance Engineer",
        "image" : "image12.png"
    },
    {
        "name": "Kavita Malhotra",
        "university": "BITS WILP",
        "course": "M.Tech in Computer Science",
        "company_name": "DevOps Dynamics Pvt. Ltd.",
        "designation": "DevOps Engineer",
        "image" : "image7.jpg"
    },
    {
        "name": "Ravi Kumar",
        "university": "BITS WILP",
        "course": "B.Tech in Information Technology",
        "company_name": "UI/UX Creators Pvt. Ltd.",
        "designation": "UI/UX Designer",
        "image" : "image13.png"
    },
    {
        "name": "Manan Iyer",
        "university": "BITS WILP",
        "course": "B.Tech in Computer Science",
        "company_name": "BigData Insights Pvt. Ltd.",
        "designation": "Big Data Analyst",
        "image" : "image14.png"
    },
    {
        "name": "Ankit Shah",
        "university": "BITS WILP",
        "course": "B.E. in Computer Science",
        "company_name": "ProjectPro Solutions Pvt. Ltd.",
        "designation": "Project Manager",
        "image" : "image15.png"
    },
]


questions = {
    "MainBranch": "What describes you the best?",
    "Employment": "Which of the following best describes your current employment status?",
    "RemoteWork": "Which best describes your current work situation?",
    "CodingActivities": "Which of the following best describes the code you write outside of work?",
    "EdLevel": "Which of the following best describes the highest level of formal education that you've completed?",
    "LearnCode": "How do you learn to code?",
    "LearnCodeOnline": "What online resources do you use to learn to code?",
    "LearnCodeCoursesCert": "What online courses or certifications do you use to learn to code? ",
    "YearsCode": "Including any education, how many years have you been coding in total?",
    "YearsCodePro": "NOT including education, how many years have you coded professionally (as a part of your work)?",
    "DevType": "Which of the following describes your current job, the one you do most of the time?",
    "Country": "Where do you live?",
    "LanguageHaveWorkedWith": "What languages have you worked with?",
    "LanguageWantToWorkWith": "What languages are you looking to work with?",
    "DatabaseHaveWorkedWith": "What databases have you worked with?",
    "DatabaseWantToWorkWith": "What databases are you looking to work with?",
    "PlatformHaveWorkedWith": "What platform have you worked on?",
    "PlatformWantToWorkWith": "What platform are you looking to work on?",
    "WebframeHaveWorkedWith": "What Webframeworks have you worked with?",
    "WebframeWantToWorkWith": "What Webframeworks do you want to work with?",
    "MiscTechHaveWorkedWith": "What other Miscellaneous Tech have you worked with?",
    "MiscTechWantToWorkWith": "What other Miscellaneous Tech do you want to work with?",
    "ToolsTechHaveWorkedWith": "Any other Tools and Technology familiar with?",
    "ToolsTechWantToWorkWith": "Any other Tools and Technology you want to get familiar with?",
    "NEWCollabToolsHaveWorkedWith": "What collaboration tools have you used?",
    "NEWCollabToolsWantToWorkWith": "Which other collaboration tools do you wish to use?",
    "ICorPM": "Are you an individual contributor or people manager?",
    "WorkExp": "How many years of working experience do you have?",
    "ProfessionalTech": "Which other professional technologies do you use?",
    "Industry": "What industry is the company you work for in?",
}
