import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { KeyValuePipe } from '@angular/common';
import { ApiService } from '../../services/api.service';
import { ToastrService } from 'ngx-toastr';
import { Router } from '@angular/router';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss'],
  providers: [KeyValuePipe] // <-- Add KeyValuePipe to providers
})
export class ProfileComponent implements OnInit {
  selectedValues: Map<string, any[]> = new Map();

  // User Information
  UserInformation: {
    username: string;
    emailAddress: string;
    firstName: string;
    lastName: string;
    company: string;
    jobTitle: string;
    university: string;
    degree: string;
  };

  // Contact Information
  ContactInformation: {
    address: string;
    city: string;
    country: string;
    postalCode: string;
  };

  // About Me
  AboutMe: {
    YearsCode: string;
    YearsCodePro: string;
    WorkExp: string;
    CodingActivities: string;
    DatabaseHaveWorkedWith: string;
    DatabaseWantToWorkWith: string;
    Employment: string;
    LanguageHaveWorkedWith: string;
    LanguageWantToWorkWith: string;
    LearnCode: string;
    LearnCodeCoursesCert: string;
    LearnCodeOnline: string;
    MiscTechHaveWorkedWith: string;
    MiscTechWantToWorkWith: string;
    NEWCollabToolsHaveWorkedWith: string;
    NEWCollabToolsWantToWorkWith: string;
    PlatformHaveWorkedWith: string;
    PlatformWantToWorkWith: string;
    ProfessionalTech: string;
    ToolsTechHaveWorkedWith: string;
    ToolsTechWantToWorkWith: string;
    WebframeHaveWorkedWith: string;
    WebframeWantToWorkWith: string;
    ICorPM: string;
    RemoteWork: string;
    EdLevel: string;
    DevType: string;
    MainBranch: string;
    Country: string;
    Industry: string;
  };

  enable = false;

  abc = ['abc'];
  mapEntries: { key: string; value: any[] }[] = [];

  constructor(
    private cdr: ChangeDetectorRef,
    private apiService: ApiService,
    private toastr: ToastrService,
    private router: Router
  ) {
    this.categorizeOptions();
    this.UserInformation = {
      username: '',
      emailAddress: '',
      firstName: '',
      lastName: '',
      company: '',
      jobTitle: '',
      university: '',
      degree: ''
    };
    this.ContactInformation = { address: '', city: '', country: '', postalCode: '' };
    this.AboutMe = {
      YearsCode: '',
      YearsCodePro: '',
      WorkExp: '',
      CodingActivities: '',
      DatabaseHaveWorkedWith: '',
      DatabaseWantToWorkWith: '',
      Employment: '',
      LanguageHaveWorkedWith: '',
      LanguageWantToWorkWith: '',
      LearnCode: '',
      LearnCodeCoursesCert: '',
      LearnCodeOnline: '',
      MiscTechHaveWorkedWith: '',
      MiscTechWantToWorkWith: '',
      NEWCollabToolsHaveWorkedWith: '',
      NEWCollabToolsWantToWorkWith: '',
      PlatformHaveWorkedWith: '',
      PlatformWantToWorkWith: '',
      ProfessionalTech: '',
      ToolsTechHaveWorkedWith: '',
      ToolsTechWantToWorkWith: '',
      WebframeHaveWorkedWith: '',
      WebframeWantToWorkWith: '',
      ICorPM: '',
      RemoteWork: '',
      EdLevel: '',
      DevType: '',
      MainBranch: '',
      Country: '',
      Industry: ''
    };
    // this.apiService.getUserProfile().subscribe(
    //   (resp) => {
    //     console.log(resp);
    //   },
    //   (err) => {}
    // );
    // this.cdr.detectChanges();
  }
  ngOnInit(): void {
    //this.categorizeOptions()
    this.cdr.detectChanges();
    this.apiService.getUserProfile().subscribe(
      (res) => {
        if (res.success === true) {
          const details = JSON.parse(res.user_details);
          console.log(details);
          this.UserInformation = details.UserInformation;
          this.ContactInformation = details.ContactInformation;
          this.AboutMe = details.AboutMe;
        } else {
          this.router.navigate(['/login']);
        }
      },
      (err) => {}
    );
  }

  // Method to handle the save button click event
  onSaveClick(): void {
    let data = { UserInformation: this.UserInformation, ContactInformation: this.ContactInformation, AboutMe: this.AboutMe };
    this.apiService.updateUserProfile(data).subscribe((res) => {
      if (res.success === true) this.toastr.success('Profile changes saved successfully!', 'Success!');
      else this.toastr.success('Some error occurred', 'Error!');
    });
  }

  categorizeOptions() {
    for (let option of this.options) {
      const [category, value] = option.split('_');
      if (this.selectedValues.has(category)) {
        let existingValues: string[] = this.selectedValues.get(category);
        existingValues.push(value);
        this.selectedValues.set(category, existingValues);
      } else {
        let existingValues: string[] = [];
        existingValues.push(value);
        this.selectedValues.set(category, existingValues);
      }
      // if (!this.selectedValues.hasOwnProperty(category)) {
      //   this.selectedValues[category] = '';
      // }
      // if (!this.selectedValues.hasOwnProperty(category + 'Options')) {
      //   this.selectedValues[category.concat('Options')] = [];
      // }
      // this.selectedValues[category + 'Options'].push({ value: option, display: value });
    }
    console.log(this.selectedValues instanceof Map);
    //console.log("selectedValues"+JSON.stringify(this.selectedValues))
    // for (let entry of this.selectedValues) {
    //   console.log('Key:', entry.);
    //   console.log('Value:', this.selectedValues[key]);
    //   this.mapEntries.push({
    //     key: key,
    //     value: this.selectedValues[key]
    //   })
    // }
    this.mapEntries = Array.from(this.selectedValues.entries()).map(([key, value]) => ({ key, value }));
    console.log('map is' + JSON.stringify(this.mapEntries));
    this.enable = true;
    this.abc.push('pqr');
    // Parse the JSON string into a JavaScript object
    const jsonObject = JSON.parse(this.questionsMap);

    // Populate the Map with key-value pairs from the JavaScript object
    Object.entries(jsonObject).forEach(([key, value]) => {
      this.myMap.set(key, value);
    });
  }

  updateValue(category: string, value: string) {
    // this.selectedValues[category] = value;
    // console.log(category + ':', this.selectedValues[category]);
  }

  // Create a new Map object
  myMap = new Map<string, any>();
  questionsMap =
    '{"MainBranch":"What describes you the best?","Employment":"Which of the following best describes your current employment status?","RemoteWork":"Which best describes your current work situation?","CodingActivities":"Which of the following best describes the code you write outside of work?","EdLevel":"Which of the following best describes the highest level of formal education that you have ve completed?","LearnCode":"How do you learn to code?","LearnCodeOnline":"What online resources do you use to learn to code?","LearnCodeCoursesCert":"What online courses or certifications do you use to learn to code? ","YearsCode":"Including any education, how many years have you been coding in total?","YearsCodePro":"NOT including education, how many years have you coded professionally (as a part of your work)?","DevType":"Which of the following describes your current job, the one you do most of the time?","Country":"Where do you live?","LanguageHaveWorkedWith":"What languages have you worked with?","LanguageWantToWorkWith":"What languages are you looking to work with?","DatabaseHaveWorkedWith":"What databases have you worked with?","DatabaseWantToWorkWith":"What databases are you looking to work with?","PlatformHaveWorkedWith":"What platform have you worked on?","PlatformWantToWorkWith":"What platform are you looking to work on?","WebframeHaveWorkedWith":"What Webframeworks have you worked with?","WebframeWantToWorkWith":"What Webframeworks do you want to work with?","MiscTechHaveWorkedWith":"What other Miscellaneous Tech have you worked with?","MiscTechWantToWorkWith":"What other Miscellaneous Tech do you want to work with?","ToolsTechHaveWorkedWith":"Any other Tools and Technology familiar with?","ToolsTechWantToWorkWith":"Any other Tools and Technology you want to get familiar with?","NEWCollabToolsHaveWorkedWith":"What collaboration tools have you used?","NEWCollabToolsWantToWorkWith":"Which other collaboration tools do you wish to use?","ICorPM":"Are you an individual contributor or people manager?","WorkExp":"How many years of working experience do you have?","ProfessionalTech":"Which other professional technologies do you use?","Industry":"What industry is the company you work for in?"}';

  options = [
    'YearsCode_>10',
    'YearsCode_>15',
    'YearsCode_>20',
    'YearsCode_>25',
    'YearsCodePro_>5',
    'YearsCodePro_>2',
    'YearsCodePro_>1',
    'YearsCodePro_>10',
    'WorkExp_>2',
    'WorkExp_>5',
    'WorkExp_>10',
    'WorkExp_>15',
    'CodingActivities_Bootstrapping a business',
    'CodingActivities_Contribute to open-source projects',
    'CodingActivities_Freelance/contract work',
    'CodingActivities_Hobby',
    "CodingActivities_I don't code outside of work",
    'CodingActivities_NA',
    'CodingActivities_Other (please specify):',
    'CodingActivities_Professional development or self-paced learning from online courses',
    'CodingActivities_School or academic work',
    'DatabaseHaveWorkedWith_BigQuery',
    'DatabaseHaveWorkedWith_Cassandra',
    'DatabaseHaveWorkedWith_Clickhouse',
    'DatabaseHaveWorkedWith_Cloud Firestore',
    'DatabaseHaveWorkedWith_Cockroachdb',
    'DatabaseHaveWorkedWith_Cosmos DB',
    'DatabaseHaveWorkedWith_Couch DB',
    'DatabaseHaveWorkedWith_Couchbase',
    'DatabaseHaveWorkedWith_Datomic',
    'DatabaseHaveWorkedWith_DuckDB',
    'DatabaseHaveWorkedWith_Dynamodb',
    'DatabaseHaveWorkedWith_Elasticsearch',
    'DatabaseHaveWorkedWith_Firebase Realtime Database',
    'DatabaseHaveWorkedWith_Firebird',
    'DatabaseHaveWorkedWith_H2',
    'DatabaseHaveWorkedWith_IBM DB2',
    'DatabaseHaveWorkedWith_InfluxDB',
    'DatabaseHaveWorkedWith_MariaDB',
    'DatabaseHaveWorkedWith_Microsoft Access',
    'DatabaseHaveWorkedWith_Microsoft SQL Server',
    'DatabaseHaveWorkedWith_MongoDB',
    'DatabaseHaveWorkedWith_MySQL',
    'DatabaseHaveWorkedWith_NA',
    'DatabaseHaveWorkedWith_Neo4J',
    'DatabaseHaveWorkedWith_Oracle',
    'DatabaseHaveWorkedWith_PostgreSQL',
    'DatabaseHaveWorkedWith_RavenDB',
    'DatabaseHaveWorkedWith_Redis',
    'DatabaseHaveWorkedWith_SQLite',
    'DatabaseHaveWorkedWith_Snowflake',
    'DatabaseHaveWorkedWith_Solr',
    'DatabaseHaveWorkedWith_Supabase',
    'DatabaseHaveWorkedWith_TiDB',
    'DatabaseWantToWorkWith_Cassandra',
    'DatabaseWantToWorkWith_BigQuery',
    'DatabaseWantToWorkWith_Clickhouse',
    'DatabaseWantToWorkWith_Cloud Firestore',
    'DatabaseWantToWorkWith_Cockroachdb',
    'DatabaseWantToWorkWith_Cosmos DB',
    'DatabaseWantToWorkWith_Couch DB',
    'DatabaseWantToWorkWith_Couchbase',
    'DatabaseWantToWorkWith_Datomic',
    'DatabaseWantToWorkWith_DuckDB',
    'DatabaseWantToWorkWith_Dynamodb',
    'DatabaseWantToWorkWith_Elasticsearch',
    'DatabaseWantToWorkWith_Firebase Realtime Database',
    'DatabaseWantToWorkWith_Firebird',
    'DatabaseWantToWorkWith_H2',
    'DatabaseWantToWorkWith_IBM DB2',
    'DatabaseWantToWorkWith_InfluxDB',
    'DatabaseWantToWorkWith_MariaDB',
    'DatabaseWantToWorkWith_Microsoft Access',
    'DatabaseWantToWorkWith_Microsoft SQL Server',
    'DatabaseWantToWorkWith_MongoDB',
    'DatabaseWantToWorkWith_MySQL',
    'DatabaseWantToWorkWith_NA',
    'DatabaseWantToWorkWith_Neo4J',
    'DatabaseWantToWorkWith_Oracle',
    'DatabaseWantToWorkWith_PostgreSQL',
    'DatabaseWantToWorkWith_RavenDB',
    'DatabaseWantToWorkWith_Redis',
    'DatabaseWantToWorkWith_SQLite',
    'DatabaseWantToWorkWith_Snowflake',
    'DatabaseWantToWorkWith_Solr',
    'DatabaseWantToWorkWith_Supabase',
    'DatabaseWantToWorkWith_TiDB',
    'Employment_Employed, full-time',
    'Employment_Employed, part-time',
    'Employment_I prefer not to say',
    'Employment_Independent contractor, freelancer, or self-employed',
    'Employment_NA',
    'Employment_Not employed, and not looking for work',
    'Employment_Not employed, but looking for work',
    'Employment_Retired',
    'Employment_Student, full-time',
    'Employment_Student, part-time',
    'LanguageHaveWorkedWith_C++',
    'LanguageHaveWorkedWith_APL',
    'LanguageHaveWorkedWith_Ada',
    'LanguageHaveWorkedWith_Apex',
    'LanguageHaveWorkedWith_Assembly',
    'LanguageHaveWorkedWith_Bash/Shell (all shells)',
    'LanguageHaveWorkedWith_C',
    'LanguageHaveWorkedWith_C#',
    'LanguageHaveWorkedWith_Clojure',
    'LanguageHaveWorkedWith_Cobol',
    'LanguageHaveWorkedWith_Crystal',
    'LanguageHaveWorkedWith_Dart',
    'LanguageHaveWorkedWith_Delphi',
    'LanguageHaveWorkedWith_Elixir',
    'LanguageHaveWorkedWith_Erlang',
    'LanguageHaveWorkedWith_F#',
    'LanguageHaveWorkedWith_Flow',
    'LanguageHaveWorkedWith_Fortran',
    'LanguageHaveWorkedWith_GDScript',
    'LanguageHaveWorkedWith_Go',
    'LanguageHaveWorkedWith_Groovy',
    'LanguageHaveWorkedWith_HTML/CSS',
    'LanguageHaveWorkedWith_Haskell',
    'LanguageHaveWorkedWith_Java',
    'LanguageHaveWorkedWith_JavaScript',
    'LanguageHaveWorkedWith_Julia',
    'LanguageHaveWorkedWith_Kotlin',
    'LanguageHaveWorkedWith_Lisp',
    'LanguageHaveWorkedWith_Lua',
    'LanguageHaveWorkedWith_MATLAB',
    'LanguageHaveWorkedWith_NA',
    'LanguageHaveWorkedWith_Nim',
    'LanguageHaveWorkedWith_OCaml',
    'LanguageHaveWorkedWith_Objective-C',
    'LanguageHaveWorkedWith_PHP',
    'LanguageHaveWorkedWith_Perl',
    'LanguageHaveWorkedWith_PowerShell',
    'LanguageHaveWorkedWith_Prolog',
    'LanguageHaveWorkedWith_Python',
    'LanguageHaveWorkedWith_R',
    'LanguageHaveWorkedWith_Raku',
    'LanguageHaveWorkedWith_Ruby',
    'LanguageHaveWorkedWith_Rust',
    'LanguageHaveWorkedWith_SAS',
    'LanguageHaveWorkedWith_SQL',
    'LanguageHaveWorkedWith_Scala',
    'LanguageHaveWorkedWith_Solidity',
    'LanguageHaveWorkedWith_Swift',
    'LanguageHaveWorkedWith_TypeScript',
    'LanguageHaveWorkedWith_VBA',
    'LanguageHaveWorkedWith_Visual Basic (.Net)',
    'LanguageHaveWorkedWith_Zig',
    'LanguageWantToWorkWith_APL',
    'LanguageWantToWorkWith_Ada',
    'LanguageWantToWorkWith_Apex',
    'LanguageWantToWorkWith_Assembly',
    'LanguageWantToWorkWith_Bash/Shell (all shells)',
    'LanguageWantToWorkWith_C',
    'LanguageWantToWorkWith_C#',
    'LanguageWantToWorkWith_C++',
    'LanguageWantToWorkWith_Clojure',
    'LanguageWantToWorkWith_Cobol',
    'LanguageWantToWorkWith_Crystal',
    'LanguageWantToWorkWith_Dart',
    'LanguageWantToWorkWith_Delphi',
    'LanguageWantToWorkWith_Elixir',
    'LanguageWantToWorkWith_Erlang',
    'LanguageWantToWorkWith_F#',
    'LanguageWantToWorkWith_Flow',
    'LanguageWantToWorkWith_Fortran',
    'LanguageWantToWorkWith_GDScript',
    'LanguageWantToWorkWith_Go',
    'LanguageWantToWorkWith_Groovy',
    'LanguageWantToWorkWith_HTML/CSS',
    'LanguageWantToWorkWith_Haskell',
    'LanguageWantToWorkWith_Java',
    'LanguageWantToWorkWith_JavaScript',
    'LanguageWantToWorkWith_Julia',
    'LanguageWantToWorkWith_Kotlin',
    'LanguageWantToWorkWith_Lisp',
    'LanguageWantToWorkWith_Lua',
    'LanguageWantToWorkWith_MATLAB',
    'LanguageWantToWorkWith_NA',
    'LanguageWantToWorkWith_Nim',
    'LanguageWantToWorkWith_OCaml',
    'LanguageWantToWorkWith_Objective-C',
    'LanguageWantToWorkWith_PHP',
    'LanguageWantToWorkWith_Perl',
    'LanguageWantToWorkWith_PowerShell',
    'LanguageWantToWorkWith_Prolog',
    'LanguageWantToWorkWith_Python',
    'LanguageWantToWorkWith_R',
    'LanguageWantToWorkWith_Raku',
    'LanguageWantToWorkWith_Ruby',
    'LanguageWantToWorkWith_Rust',
    'LanguageWantToWorkWith_SAS',
    'LanguageWantToWorkWith_SQL',
    'LanguageWantToWorkWith_Scala',
    'LanguageWantToWorkWith_Solidity',
    'LanguageWantToWorkWith_Swift',
    'LanguageWantToWorkWith_TypeScript',
    'LanguageWantToWorkWith_VBA',
    'LanguageWantToWorkWith_Visual Basic (.Net)',
    'LanguageWantToWorkWith_Zig',
    'LearnCode_Books / Physical media',
    'LearnCode_Coding Bootcamp',
    'LearnCode_Colleague',
    'LearnCode_Friend or family member',
    'LearnCode_Hackathons (virtual or in-person)',
    'LearnCode_NA',
    'LearnCode_On the job training',
    'LearnCode_Online Courses or Certification',
    'LearnCode_Other (please specify):',
    'LearnCode_Other online resources (e.g., videos, blogs, forum)',
    'LearnCode_School (i.e., University, College, etc)',
    'LearnCodeCoursesCert_Codecademy',
    'LearnCodeCoursesCert_Coursera',
    'LearnCodeCoursesCert_NA',
    'LearnCodeCoursesCert_Other',
    'LearnCodeCoursesCert_Pluralsight',
    'LearnCodeCoursesCert_Skillsoft',
    'LearnCodeCoursesCert_Udacity',
    'LearnCodeCoursesCert_Udemy',
    'LearnCodeCoursesCert_edX',
    'LearnCodeOnline_Auditory material (e.g., podcasts)',
    'LearnCodeOnline_Blogs with tips and tricks',
    'LearnCodeOnline_Books',
    'LearnCodeOnline_Certification videos',
    'LearnCodeOnline_Click to write Choice 20',
    'LearnCodeOnline_Formal documentation provided by the owner of the tech',
    'LearnCodeOnline_How-to videos',
    'LearnCodeOnline_Interactive tutorial',
    'LearnCodeOnline_NA',
    'LearnCodeOnline_Online challenges (e.g., daily or weekly coding challenges)',
    'LearnCodeOnline_Other (Please specify):',
    'LearnCodeOnline_Programming Games',
    'LearnCodeOnline_Recorded coding sessions',
    'LearnCodeOnline_Stack Overflow',
    'LearnCodeOnline_Video-based Online Courses',
    'LearnCodeOnline_Written Tutorials',
    'LearnCodeOnline_Written-based Online Courses',
    'MiscTechHaveWorkedWith_.NET (5+) ',
    'MiscTechHaveWorkedWith_.NET Framework (1.0 - 4.8)',
    'MiscTechHaveWorkedWith_.NET MAUI',
    'MiscTechHaveWorkedWith_Apache Kafka',
    'MiscTechHaveWorkedWith_Apache Spark',
    'MiscTechHaveWorkedWith_CUDA',
    'MiscTechHaveWorkedWith_Capacitor',
    'MiscTechHaveWorkedWith_Cordova',
    'MiscTechHaveWorkedWith_Electron',
    'MiscTechHaveWorkedWith_Flutter',
    'MiscTechHaveWorkedWith_GTK',
    'MiscTechHaveWorkedWith_Hadoop',
    'MiscTechHaveWorkedWith_Hugging Face Transformers',
    'MiscTechHaveWorkedWith_Ionic',
    'MiscTechHaveWorkedWith_JAX',
    'MiscTechHaveWorkedWith_Keras',
    'MiscTechHaveWorkedWith_Ktor',
    'MiscTechHaveWorkedWith_MFC',
    'MiscTechHaveWorkedWith_Micronaut',
    'MiscTechHaveWorkedWith_NA',
    'MiscTechHaveWorkedWith_NumPy',
    'MiscTechHaveWorkedWith_OpenGL',
    'MiscTechHaveWorkedWith_Opencv',
    'MiscTechHaveWorkedWith_Pandas',
    'MiscTechHaveWorkedWith_Qt',
    'MiscTechHaveWorkedWith_Quarkus',
    'MiscTechHaveWorkedWith_RabbitMQ',
    'MiscTechHaveWorkedWith_React Native',
    'MiscTechHaveWorkedWith_Scikit-Learn',
    'MiscTechHaveWorkedWith_Spring Framework',
    'MiscTechHaveWorkedWith_SwiftUI',
    'MiscTechHaveWorkedWith_Tauri',
    'MiscTechHaveWorkedWith_TensorFlow',
    'MiscTechHaveWorkedWith_Tidyverse',
    'MiscTechHaveWorkedWith_Torch/PyTorch',
    'MiscTechHaveWorkedWith_Uno Platform',
    'MiscTechHaveWorkedWith_Xamarin',
    'MiscTechWantToWorkWith_.NET (5+) ',
    'MiscTechWantToWorkWith_.NET Framework (1.0 - 4.8)',
    'MiscTechWantToWorkWith_.NET MAUI',
    'MiscTechWantToWorkWith_Apache Kafka',
    'MiscTechWantToWorkWith_Apache Spark',
    'MiscTechWantToWorkWith_CUDA',
    'MiscTechWantToWorkWith_Capacitor',
    'MiscTechWantToWorkWith_Cordova',
    'MiscTechWantToWorkWith_Electron',
    'MiscTechWantToWorkWith_Flutter',
    'MiscTechWantToWorkWith_GTK',
    'MiscTechWantToWorkWith_Hadoop',
    'MiscTechWantToWorkWith_Hugging Face Transformers',
    'MiscTechWantToWorkWith_Ionic',
    'MiscTechWantToWorkWith_JAX',
    'MiscTechWantToWorkWith_Keras',
    'MiscTechWantToWorkWith_Ktor',
    'MiscTechWantToWorkWith_MFC',
    'MiscTechWantToWorkWith_Micronaut',
    'MiscTechWantToWorkWith_NA',
    'MiscTechWantToWorkWith_NumPy',
    'MiscTechWantToWorkWith_OpenGL',
    'MiscTechWantToWorkWith_Opencv',
    'MiscTechWantToWorkWith_Pandas',
    'MiscTechWantToWorkWith_Qt',
    'MiscTechWantToWorkWith_Quarkus',
    'MiscTechWantToWorkWith_RabbitMQ',
    'MiscTechWantToWorkWith_React Native',
    'MiscTechWantToWorkWith_Scikit-Learn',
    'MiscTechWantToWorkWith_Spring Framework',
    'MiscTechWantToWorkWith_SwiftUI',
    'MiscTechWantToWorkWith_Tauri',
    'MiscTechWantToWorkWith_TensorFlow',
    'MiscTechWantToWorkWith_Tidyverse',
    'MiscTechWantToWorkWith_Torch/PyTorch',
    'MiscTechWantToWorkWith_Uno Platform',
    'MiscTechWantToWorkWith_Xamarin',
    'NEWCollabToolsHaveWorkedWith_Android Studio',
    'NEWCollabToolsHaveWorkedWith_Atom',
    'NEWCollabToolsHaveWorkedWith_BBEdit',
    'NEWCollabToolsHaveWorkedWith_CLion',
    'NEWCollabToolsHaveWorkedWith_Code::Blocks',
    'NEWCollabToolsHaveWorkedWith_DataGrip',
    'NEWCollabToolsHaveWorkedWith_Eclipse',
    'NEWCollabToolsHaveWorkedWith_Emacs',
    'NEWCollabToolsHaveWorkedWith_Fleet',
    'NEWCollabToolsHaveWorkedWith_Geany',
    'NEWCollabToolsHaveWorkedWith_Goland',
    'NEWCollabToolsHaveWorkedWith_Helix',
    'NEWCollabToolsHaveWorkedWith_IPython',
    'NEWCollabToolsHaveWorkedWith_IntelliJ IDEA',
    'NEWCollabToolsHaveWorkedWith_Jupyter Notebook/JupyterLab',
    'NEWCollabToolsHaveWorkedWith_Kate',
    'NEWCollabToolsHaveWorkedWith_Micro',
    'NEWCollabToolsHaveWorkedWith_NA',
    'NEWCollabToolsHaveWorkedWith_Nano',
    'NEWCollabToolsHaveWorkedWith_Neovim',
    'NEWCollabToolsHaveWorkedWith_Netbeans',
    'NEWCollabToolsHaveWorkedWith_Notepad++',
    'NEWCollabToolsHaveWorkedWith_Nova',
    'NEWCollabToolsHaveWorkedWith_PhpStorm',
    'NEWCollabToolsHaveWorkedWith_PyCharm',
    'NEWCollabToolsHaveWorkedWith_Qt Creator',
    'NEWCollabToolsHaveWorkedWith_RStudio',
    'NEWCollabToolsHaveWorkedWith_Rad Studio (Delphi, C++ Builder)',
    'NEWCollabToolsHaveWorkedWith_Rider',
    'NEWCollabToolsHaveWorkedWith_RubyMine',
    'NEWCollabToolsHaveWorkedWith_Spyder',
    'NEWCollabToolsHaveWorkedWith_Sublime Text',
    'NEWCollabToolsHaveWorkedWith_TextMate',
    'NEWCollabToolsHaveWorkedWith_VSCodium',
    'NEWCollabToolsHaveWorkedWith_Vim',
    'NEWCollabToolsHaveWorkedWith_Visual Studio',
    'NEWCollabToolsHaveWorkedWith_Visual Studio Code',
    'NEWCollabToolsHaveWorkedWith_WebStorm',
    'NEWCollabToolsHaveWorkedWith_Xcode',
    'NEWCollabToolsHaveWorkedWith_condo',
    'NEWCollabToolsWantToWorkWith_Android Studio',
    'NEWCollabToolsWantToWorkWith_Atom',
    'NEWCollabToolsWantToWorkWith_BBEdit',
    'NEWCollabToolsWantToWorkWith_CLion',
    'NEWCollabToolsWantToWorkWith_Code::Blocks',
    'NEWCollabToolsWantToWorkWith_DataGrip',
    'NEWCollabToolsWantToWorkWith_Eclipse',
    'NEWCollabToolsWantToWorkWith_Emacs',
    'NEWCollabToolsWantToWorkWith_Fleet',
    'NEWCollabToolsWantToWorkWith_Geany',
    'NEWCollabToolsWantToWorkWith_Goland',
    'NEWCollabToolsWantToWorkWith_Helix',
    'NEWCollabToolsWantToWorkWith_IPython',
    'NEWCollabToolsWantToWorkWith_IntelliJ IDEA',
    'NEWCollabToolsWantToWorkWith_Jupyter Notebook/JupyterLab',
    'NEWCollabToolsWantToWorkWith_Kate',
    'NEWCollabToolsWantToWorkWith_Micro',
    'NEWCollabToolsWantToWorkWith_NA',
    'NEWCollabToolsWantToWorkWith_Nano',
    'NEWCollabToolsWantToWorkWith_Neovim',
    'NEWCollabToolsWantToWorkWith_Netbeans',
    'NEWCollabToolsWantToWorkWith_Notepad++',
    'NEWCollabToolsWantToWorkWith_Nova',
    'NEWCollabToolsWantToWorkWith_PhpStorm',
    'NEWCollabToolsWantToWorkWith_PyCharm',
    'NEWCollabToolsWantToWorkWith_Qt Creator',
    'NEWCollabToolsWantToWorkWith_RStudio',
    'NEWCollabToolsWantToWorkWith_Rad Studio (Delphi, C++ Builder)',
    'NEWCollabToolsWantToWorkWith_Rider',
    'NEWCollabToolsWantToWorkWith_RubyMine',
    'NEWCollabToolsWantToWorkWith_Spyder',
    'NEWCollabToolsWantToWorkWith_Sublime Text',
    'NEWCollabToolsWantToWorkWith_TextMate',
    'NEWCollabToolsWantToWorkWith_VSCodium',
    'NEWCollabToolsWantToWorkWith_Vim',
    'NEWCollabToolsWantToWorkWith_Visual Studio',
    'NEWCollabToolsWantToWorkWith_Visual Studio Code',
    'NEWCollabToolsWantToWorkWith_WebStorm',
    'NEWCollabToolsWantToWorkWith_Xcode',
    'NEWCollabToolsWantToWorkWith_condo',
    'PlatformHaveWorkedWith_Amazon Web Services (AWS)',
    'PlatformHaveWorkedWith_Cloudflare',
    'PlatformHaveWorkedWith_Colocation',
    'PlatformHaveWorkedWith_Digital Ocean',
    'PlatformHaveWorkedWith_Firebase',
    'PlatformHaveWorkedWith_Fly.io',
    'PlatformHaveWorkedWith_Google Cloud',
    'PlatformHaveWorkedWith_Heroku',
    'PlatformHaveWorkedWith_Hetzner',
    'PlatformHaveWorkedWith_IBM Cloud Or Watson',
    'PlatformHaveWorkedWith_Linode, now Akamai',
    'PlatformHaveWorkedWith_Managed Hosting',
    'PlatformHaveWorkedWith_Microsoft Azure',
    'PlatformHaveWorkedWith_NA',
    'PlatformHaveWorkedWith_Netlify',
    'PlatformHaveWorkedWith_OVH',
    'PlatformHaveWorkedWith_OpenShift',
    'PlatformHaveWorkedWith_OpenStack',
    'PlatformHaveWorkedWith_Oracle Cloud Infrastructure (OCI)',
    'PlatformHaveWorkedWith_Render',
    'PlatformHaveWorkedWith_Scaleway',
    'PlatformHaveWorkedWith_VMware',
    'PlatformHaveWorkedWith_Vercel',
    'PlatformHaveWorkedWith_Vultr',
    'PlatformWantToWorkWith_Amazon Web Services (AWS)',
    'PlatformWantToWorkWith_Cloudflare',
    'PlatformWantToWorkWith_Colocation',
    'PlatformWantToWorkWith_Digital Ocean',
    'PlatformWantToWorkWith_Firebase',
    'PlatformWantToWorkWith_Fly.io',
    'PlatformWantToWorkWith_Google Cloud',
    'PlatformWantToWorkWith_Heroku',
    'PlatformWantToWorkWith_Hetzner',
    'PlatformWantToWorkWith_IBM Cloud Or Watson',
    'PlatformWantToWorkWith_Linode, now Akamai',
    'PlatformWantToWorkWith_Managed Hosting',
    'PlatformWantToWorkWith_Microsoft Azure',
    'PlatformWantToWorkWith_NA',
    'PlatformWantToWorkWith_Netlify',
    'PlatformWantToWorkWith_OVH',
    'PlatformWantToWorkWith_OpenShift',
    'PlatformWantToWorkWith_OpenStack',
    'PlatformWantToWorkWith_Oracle Cloud Infrastructure (OCI)',
    'PlatformWantToWorkWith_Render',
    'PlatformWantToWorkWith_Scaleway',
    'PlatformWantToWorkWith_VMware',
    'PlatformWantToWorkWith_Vercel',
    'PlatformWantToWorkWith_Vultr',
    'ProfessionalTech_AI-assisted technology tool(s)',
    'ProfessionalTech_Automated testing',
    'ProfessionalTech_Continuous integration (CI) and (more often) continuous delivery',
    'ProfessionalTech_DevOps function',
    'ProfessionalTech_Developer portal or other central places to find tools/services',
    'ProfessionalTech_Innersource initiative',
    'ProfessionalTech_Microservices',
    'ProfessionalTech_NA',
    'ProfessionalTech_None of these',
    'ProfessionalTech_Observability tools',
    'ToolsTechHaveWorkedWith_APT',
    'ToolsTechHaveWorkedWith_Ansible',
    'ToolsTechHaveWorkedWith_Ant',
    'ToolsTechHaveWorkedWith_Boost.Test',
    'ToolsTechHaveWorkedWith_Bun',
    'ToolsTechHaveWorkedWith_CMake',
    'ToolsTechHaveWorkedWith_CUTE',
    'ToolsTechHaveWorkedWith_Cargo',
    'ToolsTechHaveWorkedWith_Catch2',
    'ToolsTechHaveWorkedWith_Chef',
    'ToolsTechHaveWorkedWith_Chocolatey',
    'ToolsTechHaveWorkedWith_Composer',
    'ToolsTechHaveWorkedWith_Dagger',
    'ToolsTechHaveWorkedWith_Docker',
    'ToolsTechHaveWorkedWith_ELFspy',
    'ToolsTechHaveWorkedWith_GNU GCC',
    'ToolsTechHaveWorkedWith_Godot',
    'ToolsTechHaveWorkedWith_Google Test',
    'ToolsTechHaveWorkedWith_Gradle',
    'ToolsTechHaveWorkedWith_Homebrew',
    'ToolsTechHaveWorkedWith_Kubernetes',
    'ToolsTechHaveWorkedWith_LLVM"s Clang',
    'ToolsTechHaveWorkedWith_MSBuild',
    'ToolsTechHaveWorkedWith_MSVC',
    'ToolsTechHaveWorkedWith_Make',
    'ToolsTechHaveWorkedWith_Maven (build tool)',
    'ToolsTechHaveWorkedWith_Meson',
    'ToolsTechHaveWorkedWith_NA',
    'ToolsTechHaveWorkedWith_Ninja',
    'ToolsTechHaveWorkedWith_Nix',
    'ToolsTechHaveWorkedWith_NuGet',
    'ToolsTechHaveWorkedWith_Pacman',
    'ToolsTechHaveWorkedWith_Pip',
    'ToolsTechHaveWorkedWith_Podman',
    'ToolsTechHaveWorkedWith_Pulumi',
    'ToolsTechHaveWorkedWith_Puppet',
    'ToolsTechHaveWorkedWith_QMake',
    'ToolsTechHaveWorkedWith_SCons',
    'ToolsTechHaveWorkedWith_Terraform',
    'ToolsTechHaveWorkedWith_Unity 3D',
    'ToolsTechHaveWorkedWith_Unreal Engine',
    'ToolsTechHaveWorkedWith_Visual Studio Solution',
    'ToolsTechHaveWorkedWith_Vite',
    'ToolsTechHaveWorkedWith_Wasmer',
    'ToolsTechHaveWorkedWith_Webpack',
    'ToolsTechHaveWorkedWith_Yarn',
    'ToolsTechHaveWorkedWith_bandit',
    'ToolsTechHaveWorkedWith_build2',
    'ToolsTechHaveWorkedWith_cppunit',
    'ToolsTechHaveWorkedWith_doctest',
    'ToolsTechHaveWorkedWith_lest',
    'ToolsTechHaveWorkedWith_liblittletest',
    'ToolsTechHaveWorkedWith_npm',
    'ToolsTechHaveWorkedWith_pnpm',
    'ToolsTechHaveWorkedWith_snitch',
    'ToolsTechHaveWorkedWith_tunit',
    'ToolsTechWantToWorkWith_APT',
    'ToolsTechWantToWorkWith_Ansible',
    'ToolsTechWantToWorkWith_Ant',
    'ToolsTechWantToWorkWith_Boost.Test',
    'ToolsTechWantToWorkWith_Bun',
    'ToolsTechWantToWorkWith_CMake',
    'ToolsTechWantToWorkWith_CUTE',
    'ToolsTechWantToWorkWith_Cargo',
    'ToolsTechWantToWorkWith_Catch2',
    'ToolsTechWantToWorkWith_Chef',
    'ToolsTechWantToWorkWith_Chocolatey',
    'ToolsTechWantToWorkWith_Composer',
    'ToolsTechWantToWorkWith_Dagger',
    'ToolsTechWantToWorkWith_Docker',
    'ToolsTechWantToWorkWith_ELFspy',
    'ToolsTechWantToWorkWith_GNU GCC',
    'ToolsTechWantToWorkWith_Godot',
    'ToolsTechWantToWorkWith_Google Test',
    'ToolsTechWantToWorkWith_Gradle',
    'ToolsTechWantToWorkWith_Homebrew',
    'ToolsTechWantToWorkWith_Kubernetes',
    'ToolsTechWantToWorkWith_LLVM"s Clang',
    'ToolsTechWantToWorkWith_MSBuild',
    'ToolsTechWantToWorkWith_MSVC',
    'ToolsTechWantToWorkWith_Make',
    'ToolsTechWantToWorkWith_Maven (build tool)',
    'ToolsTechWantToWorkWith_Meson',
    'ToolsTechWantToWorkWith_NA',
    'ToolsTechWantToWorkWith_Ninja',
    'ToolsTechWantToWorkWith_Nix',
    'ToolsTechWantToWorkWith_NuGet',
    'ToolsTechWantToWorkWith_Pacman',
    'ToolsTechWantToWorkWith_Pip',
    'ToolsTechWantToWorkWith_Podman',
    'ToolsTechWantToWorkWith_Pulumi',
    'ToolsTechWantToWorkWith_Puppet',
    'ToolsTechWantToWorkWith_QMake',
    'ToolsTechWantToWorkWith_SCons',
    'ToolsTechWantToWorkWith_Terraform',
    'ToolsTechWantToWorkWith_Unity 3D',
    'ToolsTechWantToWorkWith_Unreal Engine',
    'ToolsTechWantToWorkWith_Visual Studio Solution',
    'ToolsTechWantToWorkWith_Vite',
    'ToolsTechWantToWorkWith_Wasmer',
    'ToolsTechWantToWorkWith_Webpack',
    'ToolsTechWantToWorkWith_Yarn',
    'ToolsTechWantToWorkWith_bandit',
    'ToolsTechWantToWorkWith_build2',
    'ToolsTechWantToWorkWith_cppunit',
    'ToolsTechWantToWorkWith_doctest',
    'ToolsTechWantToWorkWith_lest',
    'ToolsTechWantToWorkWith_liblittletest',
    'ToolsTechWantToWorkWith_npm',
    'ToolsTechWantToWorkWith_pnpm',
    'ToolsTechWantToWorkWith_snitch',
    'ToolsTechWantToWorkWith_tunit',
    'WebframeHaveWorkedWith_ASP.NET',
    'WebframeHaveWorkedWith_ASP.NET CORE',
    'WebframeHaveWorkedWith_Angular',
    'WebframeHaveWorkedWith_AngularJS',
    'WebframeHaveWorkedWith_Blazor',
    'WebframeHaveWorkedWith_CodeIgniter',
    'WebframeHaveWorkedWith_Deno',
    'WebframeHaveWorkedWith_Django',
    'WebframeHaveWorkedWith_Drupal',
    'WebframeHaveWorkedWith_Elm',
    'WebframeHaveWorkedWith_Express',
    'WebframeHaveWorkedWith_FastAPI',
    'WebframeHaveWorkedWith_Fastify',
    'WebframeHaveWorkedWith_Flask',
    'WebframeHaveWorkedWith_Gatsby',
    'WebframeHaveWorkedWith_Laravel',
    'WebframeHaveWorkedWith_Lit',
    'WebframeHaveWorkedWith_NA',
    'WebframeHaveWorkedWith_NestJS',
    'WebframeHaveWorkedWith_Next.js',
    'WebframeHaveWorkedWith_Node.js',
    'WebframeHaveWorkedWith_Nuxt.js',
    'WebframeHaveWorkedWith_Phoenix',
    'WebframeHaveWorkedWith_Play Framework',
    'WebframeHaveWorkedWith_Qwik',
    'WebframeHaveWorkedWith_React',
    'WebframeHaveWorkedWith_Remix',
    'WebframeHaveWorkedWith_Ruby on Rails',
    'WebframeHaveWorkedWith_Solid.js',
    'WebframeHaveWorkedWith_Spring Boot',
    'WebframeHaveWorkedWith_Svelte',
    'WebframeHaveWorkedWith_Symfony',
    'WebframeHaveWorkedWith_Vue.js',
    'WebframeHaveWorkedWith_WordPress',
    'WebframeHaveWorkedWith_jQuery',
    'WebframeWantToWorkWith_ASP.NET',
    'WebframeWantToWorkWith_ASP.NET CORE',
    'WebframeWantToWorkWith_Angular',
    'WebframeWantToWorkWith_AngularJS',
    'WebframeWantToWorkWith_Blazor',
    'WebframeWantToWorkWith_CodeIgniter',
    'WebframeWantToWorkWith_Deno',
    'WebframeWantToWorkWith_Django',
    'WebframeWantToWorkWith_Drupal',
    'WebframeWantToWorkWith_Elm',
    'WebframeWantToWorkWith_Express',
    'WebframeWantToWorkWith_FastAPI',
    'WebframeWantToWorkWith_Fastify',
    'WebframeWantToWorkWith_Flask',
    'WebframeWantToWorkWith_Gatsby',
    'WebframeWantToWorkWith_Laravel',
    'WebframeWantToWorkWith_Lit',
    'WebframeWantToWorkWith_NA',
    'WebframeWantToWorkWith_NestJS',
    'WebframeWantToWorkWith_Next.js',
    'WebframeWantToWorkWith_Node.js',
    'WebframeWantToWorkWith_Nuxt.js',
    'WebframeWantToWorkWith_Phoenix',
    'WebframeWantToWorkWith_Play Framework',
    'WebframeWantToWorkWith_Qwik',
    'WebframeWantToWorkWith_React',
    'WebframeWantToWorkWith_Remix',
    'WebframeWantToWorkWith_Ruby on Rails',
    'WebframeWantToWorkWith_Solid.js',
    'WebframeWantToWorkWith_Spring Boot',
    'WebframeWantToWorkWith_Svelte',
    'WebframeWantToWorkWith_Symfony',
    'WebframeWantToWorkWith_Vue.js',
    'WebframeWantToWorkWith_WordPress',
    'WebframeWantToWorkWith_jQuery',
    'ICorPM_NA',
    'ICorPM_People manager',
    'RemoteWork_In-person',
    'RemoteWork_NA',
    'RemoteWork_Remote',
    "EdLevel_Bachelor's degree (B.A., B.S., B.Eng., etc.)",
    "EdLevel_Master's degree (M.A., M.S., M.Eng., MBA, etc.)",
    'EdLevel_NA',
    'EdLevel_Primary/elementary school',
    'EdLevel_Professional degree (JD, MD, Ph.D, Ed.D, etc.)',
    'EdLevel_Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
    'EdLevel_Some college/university study without earning a degree',
    'EdLevel_Something else',
    'DevType_Blockchain',
    'DevType_Cloud infrastructure engineer',
    'DevType_Data or business analyst',
    'DevType_Data scientist or machine learning specialist',
    'DevType_Database administrator',
    'DevType_Designer',
    'DevType_DevOps specialist',
    'DevType_Developer Advocate',
    'DevType_Developer Experience',
    'DevType_Developer, QA or test',
    'DevType_Developer, back-end',
    'DevType_Developer, desktop or enterprise applications',
    'DevType_Developer, embedded applications or devices',
    'DevType_Developer, front-end',
    'DevType_Developer, full-stack',
    'DevType_Developer, game or graphics',
    'DevType_Developer, mobile',
    'DevType_Educator',
    'DevType_Engineer, data',
    'DevType_Engineer, site reliability',
    'DevType_Engineering manager',
    'DevType_Hardware Engineer',
    'DevType_Marketing or sales professional',
    'DevType_NA',
    'DevType_Other (please specify):',
    'DevType_Product manager',
    'DevType_Project manager',
    'DevType_Research & Development role',
    'DevType_Scientist',
    'DevType_Security professional',
    'DevType_Senior Executive (C-Suite, VP, etc.)',
    'DevType_Student',
    'DevType_System administrator',
    'MainBranch_I am learning to code',
    'MainBranch_I am not primarily a developer, but I write code sometimes as part of my work/studies',
    'MainBranch_I code primarily as a hobby',
    'MainBranch_I used to be a developer by profession, but no longer am',
    'MainBranch_None of these',
    'Country_India',
    'Country_United States of America',
    'Industry_Financial Services',
    'Industry_Healthcare',
    'Industry_Higher Education',
    'Industry_Information Services, IT, Software Development, or other Technology',
    'Industry_Insurance',
    'Industry_Legal Services',
    'Industry_Manufacturing, Transportation, or Supply Chain',
    'Industry_NA',
    'Industry_Oil & Gas',
    'Industry_Other',
    'Industry_Retail and Consumer Services',
    'Industry_Wholesale'
  ];
}
